-- Fresh-install baseline. Legacy databases are deliberately rejected by the migration runner.
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
CREATE TABLE tenants (tenant_id TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE users (
 user_id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL,
 password_hash TEXT NOT NULL, phone TEXT, active BOOLEAN NOT NULL DEFAULT true,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX users_email_normalized ON users (lower(email));
CREATE TABLE auth_sessions (
 token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(user_id),
 expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX sessions_user ON auth_sessions(user_id);
CREATE TABLE login_attempts (bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, expires_at TIMESTAMPTZ NOT NULL);


CREATE TABLE customers (
        tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
        customer_id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        company TEXT NOT NULL,
        phone TEXT NOT NULL,
        email TEXT NOT NULL,
        address TEXT NOT NULL,
        total_shipments INTEGER DEFAULT 0,
        total_spent NUMERIC(16,2) DEFAULT 0.0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    ,
        UNIQUE (tenant_id, customer_id)
    );

CREATE UNIQUE INDEX customers_email_tenant ON customers(tenant_id, email);

CREATE TABLE vehicles (
        tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
        vehicle_id TEXT PRIMARY KEY,
        registration_number TEXT NOT NULL,
        vehicle_type TEXT NOT NULL,
        make TEXT NOT NULL,
        model TEXT NOT NULL,
        year INTEGER NOT NULL,
        capacity_mt NUMERIC(16,2) NOT NULL,
        fuel_type TEXT NOT NULL,
        current_location TEXT NOT NULL,
        assigned_driver_id TEXT,
        insurance_expiry DATE NOT NULL,
        permit_expiry DATE NOT NULL,
        fitness_expiry DATE NOT NULL,
        service_due_date DATE NOT NULL,
        status TEXT NOT NULL CHECK(status IN ('Available', 'On Trip', 'Maintenance', 'Inactive')),
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    ,
        UNIQUE (tenant_id, vehicle_id)
    );

CREATE UNIQUE INDEX vehicles_registration_number_tenant ON vehicles(tenant_id, registration_number);

CREATE TABLE drivers (
        tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
        driver_id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        phone TEXT NOT NULL,
        email TEXT NOT NULL,
        license_number TEXT NOT NULL,
        license_expiry DATE NOT NULL,
        address TEXT NOT NULL,
        experience_years INTEGER NOT NULL,
        assigned_vehicle_id TEXT,
        status TEXT NOT NULL CHECK(status IN ('Available', 'On Trip', 'Off Duty', 'Suspended')),
        total_trips INTEGER DEFAULT 0,
        completed_trips INTEGER DEFAULT 0,
        rating NUMERIC(16,2) DEFAULT 5.0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    ,
        UNIQUE (tenant_id, driver_id)
    );

CREATE UNIQUE INDEX drivers_email_tenant ON drivers(tenant_id, email);

CREATE UNIQUE INDEX drivers_license_number_tenant ON drivers(tenant_id, license_number);

CREATE TABLE shipments (
        tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
        shipment_id TEXT PRIMARY KEY,
        customer_id TEXT NOT NULL,
        customer_name TEXT NOT NULL,
        pickup_location TEXT NOT NULL,
        destination TEXT NOT NULL,
        goods_type TEXT NOT NULL,
        description TEXT,
        weight_kg NUMERIC(16,2) NOT NULL,
        quantity INTEGER NOT NULL,
        vehicle_id TEXT,
        vehicle_reg TEXT,
        driver_id TEXT,
        driver_name TEXT,
        status TEXT NOT NULL CHECK(status IN (
            'Booked', 'Confirmed', 'Picked Up', 'At Warehouse',
            'In Transit', 'Out for Delivery', 'Delivered', 'Delayed', 'Cancelled', 'Returned'
        )),
        booking_date DATE NOT NULL,
        expected_delivery DATE NOT NULL,
        shipping_cost NUMERIC(16,2) NOT NULL,
        payment_method TEXT NOT NULL,
        payment_status TEXT NOT NULL CHECK(payment_status IN ('Pending', 'Paid', 'Failed', 'Refunded')),
        special_instructions TEXT,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(tenant_id, customer_id) REFERENCES customers(tenant_id, customer_id)
    ,
        UNIQUE (tenant_id, shipment_id)
    );

CREATE TABLE shipment_status_history (
        tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
        history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        shipment_id TEXT NOT NULL,
        status TEXT NOT NULL,
        timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        location TEXT NOT NULL,
        updated_by TEXT NOT NULL,
        notes TEXT,
        FOREIGN KEY(tenant_id, shipment_id) REFERENCES shipments(tenant_id, shipment_id) ON DELETE CASCADE
    ,
        UNIQUE (tenant_id, history_id)
    );

CREATE TABLE routes (
        tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
        route_id TEXT PRIMARY KEY,
        pickup TEXT NOT NULL,
        destination TEXT NOT NULL,
        distance_km NUMERIC(16,2) NOT NULL,
        estimated_time TEXT NOT NULL,
        fuel_cost_est NUMERIC(16,2) NOT NULL,
        recommended_route TEXT NOT NULL,
        stops_json TEXT,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    ,
        UNIQUE (tenant_id, route_id)
    );

CREATE TABLE warehouses (
        tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
        warehouse_id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        location TEXT NOT NULL,
        manager_name TEXT NOT NULL,
        contact_phone TEXT NOT NULL,
        capacity_tons NUMERIC(16,2) NOT NULL,
        current_occupancy_tons NUMERIC(16,2) NOT NULL,
        status TEXT NOT NULL CHECK(status IN ('Active', 'Full', 'Maintenance')),
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    ,
        UNIQUE (tenant_id, warehouse_id)
    );

CREATE TABLE deliveries (
        tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
        delivery_id TEXT PRIMARY KEY,
        shipment_id TEXT NOT NULL,
        customer_name TEXT NOT NULL,
        driver_id TEXT,
        vehicle_reg TEXT,
        pickup TEXT NOT NULL,
        destination TEXT NOT NULL,
        expected_delivery DATE NOT NULL,
        actual_delivery TIMESTAMPTZ,
        status TEXT NOT NULL CHECK(status IN ('Pending', 'In Progress', 'Delivered', 'Failed')),
        otp_code TEXT NOT NULL,
        otp_attempts INTEGER NOT NULL DEFAULT 0,
        otp_expires_at TIMESTAMPTZ,
        receiver_name TEXT,
        delivery_notes TEXT,
        signature_data TEXT,
        FOREIGN KEY(tenant_id, shipment_id) REFERENCES shipments(tenant_id, shipment_id) ON DELETE CASCADE
    ,
        UNIQUE (tenant_id, delivery_id)
    );

CREATE UNIQUE INDEX deliveries_shipment_id_tenant ON deliveries(tenant_id, shipment_id);

CREATE TABLE payments (
        tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
        invoice_id TEXT PRIMARY KEY,
        shipment_id TEXT NOT NULL,
        customer_name TEXT NOT NULL,
        amount NUMERIC(16,2) NOT NULL,
        tax_amount NUMERIC(16,2) NOT NULL,
        total_amount NUMERIC(16,2) NOT NULL,
        payment_method TEXT NOT NULL,
        payment_status TEXT NOT NULL CHECK(payment_status IN ('Pending', 'Paid', 'Failed', 'Refunded')),
        invoice_date DATE NOT NULL,
        paid_date DATE,
        FOREIGN KEY(tenant_id, shipment_id) REFERENCES shipments(tenant_id, shipment_id) ON DELETE CASCADE
    ,
        UNIQUE (tenant_id, invoice_id)
    );

CREATE UNIQUE INDEX payments_shipment_id_tenant ON payments(tenant_id, shipment_id);

CREATE TABLE notifications (
        tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
        notification_id TEXT PRIMARY KEY,
        user_role TEXT,
        title TEXT NOT NULL,
        message TEXT NOT NULL,
        type TEXT NOT NULL CHECK(type IN ('info', 'success', 'warning', 'danger')),
        recipient_user_id TEXT REFERENCES users(user_id),
        timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    ,
        UNIQUE (tenant_id, notification_id)
    );

CREATE TABLE maintenance_records (
        tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
        record_id TEXT PRIMARY KEY,
        vehicle_id TEXT NOT NULL,
        service_type TEXT NOT NULL,
        cost NUMERIC(16,2) NOT NULL,
        service_date DATE NOT NULL,
        next_due_date DATE NOT NULL,
        status TEXT NOT NULL,
        notes TEXT,
        FOREIGN KEY(tenant_id, vehicle_id) REFERENCES vehicles(tenant_id, vehicle_id)
    ,
        UNIQUE (tenant_id, record_id)
    );


CREATE TABLE memberships (
 tenant_id TEXT NOT NULL REFERENCES tenants(tenant_id),
 user_id TEXT NOT NULL REFERENCES users(user_id),
 role TEXT NOT NULL CHECK(role IN ('ADMIN','MANAGER','DRIVER','CUSTOMER')),
 customer_id TEXT, driver_id TEXT,
 PRIMARY KEY (tenant_id, user_id),
 FOREIGN KEY (tenant_id, customer_id) REFERENCES customers(tenant_id, customer_id),
 FOREIGN KEY (tenant_id, driver_id) REFERENCES drivers(tenant_id, driver_id),
 CHECK ((role = 'CUSTOMER' AND customer_id IS NOT NULL AND driver_id IS NULL)
     OR (role = 'DRIVER' AND driver_id IS NOT NULL AND customer_id IS NULL)
     OR (role IN ('ADMIN','MANAGER') AND customer_id IS NULL AND driver_id IS NULL))
);
ALTER TABLE shipments ADD FOREIGN KEY (tenant_id, driver_id) REFERENCES drivers(tenant_id, driver_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE shipments ADD FOREIGN KEY (tenant_id, vehicle_id) REFERENCES vehicles(tenant_id, vehicle_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE deliveries ADD FOREIGN KEY (tenant_id, driver_id) REFERENCES drivers(tenant_id, driver_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE vehicles ADD FOREIGN KEY (tenant_id, assigned_driver_id) REFERENCES drivers(tenant_id, driver_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE drivers ADD FOREIGN KEY (tenant_id, assigned_vehicle_id) REFERENCES vehicles(tenant_id, vehicle_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE shipments ADD CHECK (weight_kg > 0 AND weight_kg <= 100000 AND quantity BETWEEN 1 AND 100000 AND shipping_cost >= 0);
ALTER TABLE payments ADD CHECK (amount >= 0 AND tax_amount >= 0 AND total_amount = amount + tax_amount);
ALTER TABLE deliveries ADD CHECK (otp_attempts BETWEEN 0 AND 5);
ALTER TABLE vehicles ADD CHECK (capacity_mt > 0 AND capacity_mt <= 200);
ALTER TABLE warehouses ADD CHECK (capacity_tons >= 0 AND current_occupancy_tons BETWEEN 0 AND capacity_tons);
-- Membership-backed RLS context: an arbitrary tenant setting is not authority.
CREATE FUNCTION authorized_tenant_id() RETURNS TEXT LANGUAGE sql STABLE SET search_path = pg_catalog, public AS $$
 SELECT tenant_id FROM public.memberships
 WHERE user_id = nullif(current_setting('app.principal_id', true), '')
 AND tenant_id = nullif(current_setting('app.tenant_id', true), '')
$$;
REVOKE ALL ON FUNCTION authorized_tenant_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION authorized_tenant_id() TO apex_app;

CREATE TABLE notification_reads (
 tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
 notification_id TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(user_id),
 read_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY (tenant_id, notification_id, user_id),
 FOREIGN KEY (tenant_id, notification_id) REFERENCES notifications(tenant_id, notification_id) ON DELETE CASCADE
);
ALTER TABLE notification_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_reads FORCE ROW LEVEL SECURITY;
CREATE POLICY own_notification_reads ON notification_reads
 USING (tenant_id = (SELECT authorized_tenant_id()) AND user_id = nullif(current_setting('app.principal_id',true),''))
 WITH CHECK (tenant_id = (SELECT authorized_tenant_id()) AND user_id = nullif(current_setting('app.principal_id',true),''));
GRANT SELECT, INSERT ON notification_reads TO apex_app;

CREATE TABLE idempotency_records (
 tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
 user_id TEXT NOT NULL REFERENCES users(user_id), key TEXT NOT NULL,
 fingerprint TEXT NOT NULL, authorization_context TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('PENDING','COMPLETED','FAILED')),
 status_code INTEGER, response_body TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 PRIMARY KEY (tenant_id, user_id, key),
 CHECK ((state = 'PENDING' AND status_code IS NULL AND response_body IS NULL)
 OR (state <> 'PENDING' AND status_code BETWEEN 200 AND 499 AND response_body IS NOT NULL))
);
CREATE TABLE audit_events (
 tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
 event_id UUID PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(user_id),
 operation TEXT NOT NULL, status_code INTEGER NOT NULL, request_key TEXT NOT NULL, resource_id TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE outbox_events (
 tenant_id TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), '') REFERENCES tenants(tenant_id),
 event_id UUID PRIMARY KEY, kind TEXT NOT NULL, payload TEXT NOT NULL,
 state TEXT NOT NULL DEFAULT 'PENDING' CHECK(state IN ('PENDING','COMPLETED','FAILED')),
 attempts INTEGER NOT NULL DEFAULT 0, available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), delivered_at TIMESTAMPTZ
);


ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON customers USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON vehicles USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE drivers FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON drivers USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipments FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON shipments USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE shipment_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipment_status_history FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON shipment_status_history USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE routes FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON routes USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE warehouses FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON warehouses USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON deliveries USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON payments USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON notifications USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE maintenance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_records FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON maintenance_records USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE idempotency_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE idempotency_records FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON idempotency_records USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON audit_events USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE outbox_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbox_events FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON outbox_events USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));

ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON tenants USING (tenant_id = (SELECT authorized_tenant_id())) WITH CHECK (tenant_id = (SELECT authorized_tenant_id()));


ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE memberships FORCE ROW LEVEL SECURITY;
CREATE POLICY own_memberships ON memberships USING (user_id = nullif(current_setting('app.principal_id', true), ''));
GRANT USAGE ON SCHEMA public TO apex_app;
GRANT SELECT ON tenants, memberships TO apex_app;
GRANT SELECT ON users TO apex_app;
GRANT SELECT, INSERT, DELETE ON auth_sessions TO apex_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON login_attempts TO apex_app;


GRANT SELECT, INSERT ON customers TO apex_app;

GRANT SELECT, INSERT ON vehicles TO apex_app;

GRANT SELECT, INSERT ON drivers TO apex_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON shipments TO apex_app;

GRANT SELECT, INSERT, DELETE ON shipment_status_history TO apex_app;

GRANT SELECT ON routes TO apex_app;

GRANT SELECT ON warehouses TO apex_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON deliveries TO apex_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON payments TO apex_app;

GRANT SELECT, INSERT ON notifications TO apex_app;

GRANT SELECT ON maintenance_records TO apex_app;

GRANT SELECT, INSERT ON idempotency_records TO apex_app;
GRANT UPDATE(fingerprint, state, status_code, response_body) ON idempotency_records TO apex_app;

GRANT SELECT, INSERT ON audit_events TO apex_app;

GRANT SELECT, INSERT ON outbox_events TO apex_app;
GRANT UPDATE(state, attempts, available_at, delivered_at) ON outbox_events TO apex_app;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO apex_app;

ALTER TABLE customers ADD CHECK (total_spent <> 'NaN'::numeric);
ALTER TABLE vehicles ADD CHECK (capacity_mt <> 'NaN'::numeric);
ALTER TABLE drivers ADD CHECK (rating <> 'NaN'::numeric);
ALTER TABLE shipments ADD CHECK (weight_kg <> 'NaN'::numeric);
ALTER TABLE shipments ADD CHECK (shipping_cost <> 'NaN'::numeric);
ALTER TABLE routes ADD CHECK (distance_km <> 'NaN'::numeric);
ALTER TABLE routes ADD CHECK (fuel_cost_est <> 'NaN'::numeric);
ALTER TABLE warehouses ADD CHECK (capacity_tons <> 'NaN'::numeric);
ALTER TABLE warehouses ADD CHECK (current_occupancy_tons <> 'NaN'::numeric);
ALTER TABLE payments ADD CHECK (amount <> 'NaN'::numeric);
ALTER TABLE payments ADD CHECK (tax_amount <> 'NaN'::numeric);
ALTER TABLE payments ADD CHECK (total_amount <> 'NaN'::numeric);
ALTER TABLE maintenance_records ADD CHECK (cost <> 'NaN'::numeric);

ALTER TABLE notifications ADD FOREIGN KEY (tenant_id, recipient_user_id)
 REFERENCES memberships(tenant_id, user_id) ON DELETE SET NULL (recipient_user_id);
